'use server';

/**
 * @fileOverview An AI-driven tool that provides interactive tutorials and explanations about different aiming techniques, ethical considerations, and the implications of using aim-assist or aimlock systems.
 *
 * - interactiveAimingTutorials - A function that provides interactive tutorials and explanations about aiming techniques.
 * - InteractiveAimingTutorialsInput - The input type for the interactiveAimingTutorials function.
 * - InteractiveAimingTutorialsOutput - The return type for the interactiveAimingTutorials function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const InteractiveAimingTutorialsInputSchema = z.object({
  topic: z
    .string()
    .describe(
      'The specific topic about aiming techniques, ethical considerations, or implications of aim-assist or aimlock systems that the user wants to learn about.'
    ),
});
export type InteractiveAimingTutorialsInput = z.infer<typeof InteractiveAimingTutorialsInputSchema>;

const InteractiveAimingTutorialsOutputSchema = z.object({
  tutorialContent: z.string().describe('The interactive tutorial content generated by the AI.'),
});
export type InteractiveAimingTutorialsOutput = z.infer<typeof InteractiveAimingTutorialsOutputSchema>;

export async function interactiveAimingTutorials(input: InteractiveAimingTutorialsInput): Promise<InteractiveAimingTutorialsOutput> {
  return interactiveAimingTutorialsFlow(input);
}

const interactiveAimingTutorialsPrompt = ai.definePrompt({
  name: 'interactiveAimingTutorialsPrompt',
  input: {schema: InteractiveAimingTutorialsInputSchema},
  output: {schema: InteractiveAimingTutorialsOutputSchema},
  prompt: `You are an AI-driven tool that provides interactive tutorials and explanations about different aiming techniques, ethical considerations, and the implications of using aim-assist or aimlock systems.

  The user wants to learn about: {{{topic}}}

  Generate an interactive tutorial that explains the topic in detail. Include examples, ethical considerations, and implications where applicable. Make the tutorial engaging and easy to understand.
  `,
});

const interactiveAimingTutorialsFlow = ai.defineFlow(
  {
    name: 'interactiveAimingTutorialsFlow',
    inputSchema: InteractiveAimingTutorialsInputSchema,
    outputSchema: InteractiveAimingTutorialsOutputSchema,
  },
  async input => {
    const {output} = await interactiveAimingTutorialsPrompt(input);
    return output!;
  }
);
